### ISSUE TITLE
Could you share the demo code of Carla ?

### ISSUE THREAD

**Issue by joeking11829** [kuriatsu/ros-g29-force-feedback#11]
Hi @kuriatsu ,

Thanks for your great works.

As the title says,
Could you share the demo code of Carla ?

Thanks you.

![image](https://user-images.githubusercontent.com/5969040/172355727-4c3f3f95-a426-412f-8c1f-b68e5e7e3eaa.png)

**Comment by kuriatsu** [comment]
That's like getting control information from carla and rotate the wheel according to it?

**Comment by kuriatsu** [comment]
You wanna control the vehicle using the wheel at the same time?
Like bidirectional (cooperative) driving.
If so, it will take time to provide.

**Comment by joeking11829** [comment]
Hi @kuriatsu ,

I wanna sync the vehicle's steer to G29 controller smoothly and continuously

I have some questions.
1. Does it accept loop_rate = 0.05 s ( 50ms ) ?
2. What is the minimum moving position ? ( like 0.01 ? )

How should set the config.yaml ?

Thanks !!

**Comment by kuriatsu** [comment]
Sorry for the late reply. 
I completely missed it.
1. I'm not sure whether it's possible or not, because even 0.1s, I could not confirm that the g29 accepts the change. Please try.
2. The latest version removed the parameter.

Basically, what you have to change is `device_name` in yaml file.
Please tweak the parameter as you need referring the documentation.

**Comment by kuriatsu** [comment]
And I added the test code to sync the vehicle in the carla (rolename="hero" or "ego_vehicle").
Try `python3 examples/carla_control.py`

**Comment by joeking11829** [comment]
@kuriatsu 
Thanks for the reply.
